//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Button_State : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Trigger_dx
        {
            get
            {
                return SteamVR_Actions.button_State_Trigger_dx;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu_dx
        {
            get
            {
                return SteamVR_Actions.button_State_Menu_dx;
            }
        }
        
        public virtual SteamVR_Action_Boolean System_dx
        {
            get
            {
                return SteamVR_Actions.button_State_System_dx;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touch_Pad_dx
        {
            get
            {
                return SteamVR_Actions.button_State_Touch_Pad_dx;
            }
        }
        
        public virtual SteamVR_Action_Boolean Gripper_dx
        {
            get
            {
                return SteamVR_Actions.button_State_Gripper_dx;
            }
        }
        
        public virtual SteamVR_Action_Boolean Trigger_sx
        {
            get
            {
                return SteamVR_Actions.button_State_Trigger_sx;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu_sx
        {
            get
            {
                return SteamVR_Actions.button_State_Menu_sx;
            }
        }
        
        public virtual SteamVR_Action_Boolean System_sx
        {
            get
            {
                return SteamVR_Actions.button_State_System_sx;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touch_Pad_sx
        {
            get
            {
                return SteamVR_Actions.button_State_Touch_Pad_sx;
            }
        }
        
        public virtual SteamVR_Action_Boolean Gripper_sx
        {
            get
            {
                return SteamVR_Actions.button_State_Gripper_sx;
            }
        }
    }
}
